WebApp/Controllers/PartialController.cs
using Common.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json;

namespace WebApp.Controllers
{
    public class PartialController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DiseaseList()
        {

            List<DiseaseInformationModel> list = new List<DiseaseInformationModel>();

            try
            {
                string url = string.Format("{0}/api/Disease", Utils.BaseUrl);

                HttpClient httpClient = new HttpClient();

                ClaimsPrincipal user = HttpContext.User;

                // Retrieve the SerialNumber claim
                string serialNumberClaim = user.FindFirst(ClaimTypes.SerialNumber).Value;

                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + serialNumberClaim);

                // Add any custom headers
                HttpResponseMessage result = await httpClient.GetAsync(url);
                if (result.IsSuccessStatusCode)
                {
                    var response = await result.Content.ReadFromJsonAsync<Res>();

                    if (response.Status)
                    {
                        //Save the token, decrypt and get user claims and save to secured storage.

                        list = JsonSerializer.Deserialize<List<DiseaseInformationModel>>(response.Data.ToString());

                    }
                    else
                    {
                        Console.WriteLine(response.Message);

                    }

                }
                else
                {
                    Console.WriteLine(result.ReasonPhrase.ToString());
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return PartialView(list);
        }

        [HttpGet]
        public async Task<IActionResult> NcdList()
        {

            List<NCDModel> list = new List<NCDModel>();

            try
            {
                string url = string.Format("{0}/api/NCD", Utils.BaseUrl);

                HttpClient httpClient = new HttpClient();

                ClaimsPrincipal user = HttpContext.User;

                // Retrieve the SerialNumber claim
                string serialNumberClaim = user.FindFirst(ClaimTypes.SerialNumber).Value;

                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + serialNumberClaim);

                // Add any custom headers
                HttpResponseMessage result = await httpClient.GetAsync(url);
                if (result.IsSuccessStatusCode)
                {
                    var response = await result.Content.ReadFromJsonAsync<Res>();

                    if (response.Status)
                    {
                        //Save the token, decrypt and get user claims and save to secured storage.

                        list = JsonSerializer.Deserialize<List<NCDModel>>(response.Data.ToString());

                    }
                    else
                    {
                        Console.WriteLine(response.Message);

                    }

                }
                else
                {
                    Console.WriteLine(result.ReasonPhrase.ToString());
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return PartialView(list);
        }

        [HttpGet]
        public async Task<IActionResult> AllergiesList()
        {

            List<AllergiesModel> list = new List<AllergiesModel>();

            try
            {
                string url = string.Format("{0}/api/Allergies", Utils.BaseUrl);

                HttpClient httpClient = new HttpClient();

                ClaimsPrincipal user = HttpContext.User;

                // Retrieve the SerialNumber claim
                string serialNumberClaim = user.FindFirst(ClaimTypes.SerialNumber).Value;

                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + serialNumberClaim);

                // Add any custom headers
                HttpResponseMessage result = await httpClient.GetAsync(url);
                if (result.IsSuccessStatusCode)
                {
                    var response = await result.Content.ReadFromJsonAsync<Res>();

                    if (response.Status)
                    {
                        //Save the token, decrypt and get user claims and save to secured storage.

                        list = JsonSerializer.Deserialize<List<AllergiesModel>>(response.Data.ToString());

                    }
                    else
                    {
                        Console.WriteLine(response.Message);

                    }

                }
                else
                {
                    Console.WriteLine(result.ReasonPhrase.ToString());
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return PartialView(list);
        }

        [HttpGet]
        public async Task<IActionResult> PatientList()
        {

            List<PatientsModel> list = new List<PatientsModel>();

            try
            {
                string url = string.Format("{0}/api/Patient", Utils.BaseUrl);

                HttpClient httpClient = new HttpClient();

                ClaimsPrincipal user = HttpContext.User;

                // Retrieve the SerialNumber claim
                string serialNumberClaim = user.FindFirst(ClaimTypes.SerialNumber).Value;

                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + serialNumberClaim);

                // Add any custom headers
                HttpResponseMessage result = await httpClient.GetAsync(url);
                if (result.IsSuccessStatusCode)
                {
                    var response = await result.Content.ReadFromJsonAsync<Res>();

                    if (response.Status)
                    {
                        //Save the token, decrypt and get user claims and save to secured storage.

                        list = JsonSerializer.Deserialize<List<PatientsModel>>(response.Data.ToString());

                    }
                    else
                    {
                        Console.WriteLine(response.Message);

                    }

                }
                else
                {
                    Console.WriteLine(result.ReasonPhrase.ToString());
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return PartialView(list);
        }

        [HttpGet]
        public async Task<IActionResult> PatientsDetails(long id)
        {

           PatientDetailsModel list = new PatientDetailsModel();

            try
            {
                string url = string.Format("{0}/api/Patient/{1}", Utils.BaseUrl, id);

                HttpClient httpClient = new HttpClient();

                ClaimsPrincipal user = HttpContext.User;

                // Retrieve the SerialNumber claim
                string serialNumberClaim = user.FindFirst(ClaimTypes.SerialNumber).Value;

                httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + serialNumberClaim);

                // Add any custom headers
                HttpResponseMessage result = await httpClient.GetAsync(url);
                if (result.IsSuccessStatusCode)
                {
                    var response = await result.Content.ReadFromJsonAsync<Res>();

                    if (response.Status)
                    {
                        //Save the token, decrypt and get user claims and save to secured storage.

                        list = JsonSerializer.Deserialize<PatientDetailsModel>(response.Data.ToString());

                    }
                    else
                    {
                        Console.WriteLine(response.Message);

                    }

                }
                else
                {
                    Console.WriteLine(result.ReasonPhrase.ToString());
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            return PartialView(list);
        }
    }
}

WebApp/Views/Shared/_Allergies.cshtml
<div class="row mt-3">

    <div class="col-md-3">

        <input type="text"
               id="newAllergies"
               class="form-control" placeholder="Allergies Name" />

    </div>

    <div class="col-md-2">

        <button type="button"
                id="saveAllergies"
                data-id="0"
                class="btn btn-success disabled">
            Save
        </button>


    </div>

    <div class="col-md-4">
        <div id="resultAllergies"></div>
    </div>

</div>

<div class="row  mt-2">

    <div class="col-md-12"
         style="height: 250px; overflow-y: scroll">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody id="allergiesList">
            </tbody>
        </table>

        <div class="allergiesListLoader">
            <div style="text-align: center">
                <img src="~/assets/images/loader.gif" />
            </div>
        </div>

    </div>

</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    $(document).ready(function (e) {


        AllergiesLoad();

    });


    $(document).on("keyup", "#newAllergies", function (e) {

        $('#resultAllergies').html("");

        if ($(this).val().trim() == "") {

            $("#saveAllergies").addClass("disabled");

        } else {

            $("#saveAllergies").removeClass("disabled");
        }

    });



    $(document).on("click", "#saveAllergies", function (e) {

        ButtonLoaderShow("#saveAllergies");

        var id = 0;

        if ($(this).text() == "Update") {

            id = $(this).attr("data-id");

        }

        var data = {
            ID: id,
            Name: $("#newAllergies").val()
        }


        $.ajax({
            url: '@Url.Action("AllergiesSave", "Home")',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(data),
            success: function (res) {

                if (res.error == "") {

                    $('#resultAllergies').html(res.message);
                    $("#saveAllergies").text("Save");
                    AllergiesLoad();

                } else {

                    $('#resultAllergies').html(res.error);

                }

            },
            error: function (xhr, status, error) {
                $('#resultAllergies').html('<p>An error occurred: ' + error + '</p>');
            }
        });

    });

    $(document).on("click", ".allergiesListEdit", function (e) {

        var data = $(this).parents("tr");

        var id = data.attr("data-id");
        var name = data.attr("data-name");

        $("#saveAllergies").attr("data-id", id);
        $("#newAllergies").val(name);

        $("#saveAllergies").removeClass("disabled");
        $("#saveAllergies").text("Update");
        $("#resultAllergies").html("");
    });

    $(document).on("click", ".allergiesListDelete", function (e) {

        var parent = $(this).parents("tr");
        var id = parent.attr("data-id");
        parent.remove();

        $.ajax({
            url: 'Home/AllergiesDelete/' + id,
            type: 'POST',
            contentType: 'application/json',
            success: function (res) {

                if (res.error == "") {

                    $("#saveAllergies").text("Save");
                    $('#resultAllergies').html(res.message);


                } else {

                    $('#resultAllergies').html(res.error);

                }

            },
            error: function (xhr, status, error) {
                $('#resultAllergies').html('<p>An error occurred: ' + error + '</p>');
            }
        });





    });

    function AllergiesLoad() {

        LoaderOneShow(".allergiesListLoader");

        $.ajax({
            url: '@Url.Action("AllergiesList", "Partial")',
            type: 'GET',
            dataType: 'html',
            success: function (res) {

                LoaderOneHide(".allergiesListLoader");
                $("#allergiesList").html(res);

            },
            error: function (xhr, status, error) {

                $('#resultAllergies').html('<p>An error occurred: ' + error + '</p>');

            }
        });

    }

</script>

WebApp/Views/Shared/_Disease.cshtml
<div class="row mt-3">

    <div class="col-md-3">

        <input type="text"
               id="newDisease"
               class="form-control" placeholder="Disease Name" />

    </div>

    <div class="col-md-2">

        <button type="button"
                id="saveDisease"
                data-id="0"
                class="btn btn-success disabled">
            Save
        </button>


    </div>

    <div class="col-md-4">
        <div id="resultDisease"></div>
    </div>

</div>

<div class="row  mt-2">

    <div class="col-md-12"
         style="height: 250px; overflow-y: scroll">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody id="diseaseList">
            </tbody>
        </table>

        <div class="diseaseListLoader">
            <div style="text-align: center">
                <img src="~/assets/images/loader.gif" />
            </div>
        </div>
    </div>

</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    $(document).ready(function (e) {


        DiseaseLoad();

    });


    $(document).on("keyup", "#newDisease", function (e) {

        $('#resultDisease').html("");

        if ($(this).val().trim() == "") {

            $("#saveDisease").addClass("disabled");

        } else {

            $("#saveDisease").removeClass("disabled");
        }

    });



    $(document).on("click", "#saveDisease", function (e) {


        ButtonLoaderShow("#saveDisease");

        var id = 0;

        if ($(this).text() == "Update") {

            id = $(this).attr("data-id");

        }

        var data = {
            ID: id,
            Name: $("#newDisease").val()
        }


        $.ajax({
            url: '@Url.Action("DiseaseSave", "Home")',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(data),
            success: function (res) {

                if (res.error == "") {

                    $('#resultDisease').html(res.message);
                    $("#saveDisease").text("Save");
                    DiseaseLoad();

                } else {

                    $('#resultDisease').html(res.error);

                }

            },
            error: function (xhr, status, error) {
                $('#resultDisease').html('<p>An error occurred: ' + error + '</p>');
            }
        });

    });

    $(document).on("click", ".diseaseListEdit", function (e) {

        var data = $(this).parents("tr");

        var id = data.attr("data-id");
        var name = data.attr("data-name");

        $("#saveDisease").attr("data-id", id);
        $("#newDisease").val(name);

        $("#saveDisease").removeClass("disabled");
        $("#saveDisease").text("Update");
        $("#resultDisease").html("");
    });

    $(document).on("click", ".diseaseListDelete", function (e) {

        var parent = $(this).parents("tr");
        var id = parent.attr("data-id");
        parent.remove();

        $.ajax({
            url: 'Home/DiseaseDelete/' + id,
            type: 'POST',
            contentType: 'application/json',
            success: function (res) {

                if (res.error == "") {

                    $("#saveDisease").text("Save");
                    $('#resultDisease').html(res.message);


                } else {

                    $('#resultDisease').html(res.error);

                }

            },
            error: function (xhr, status, error) {
                $('#resultDisease').html('<p>An error occurred: ' + error + '</p>');
            }
        });





    });

    function DiseaseLoad() {

        LoaderOneShow(".diseaseListLoader");

        $.ajax({
            url: '@Url.Action("DiseaseList", "Partial")',
            type: 'GET',
            dataType: 'html',
            success: function (res) {

                LoaderOneHide(".diseaseListLoader");
                $("#diseaseList").html(res);

            },
            error: function (xhr, status, error) {

                $('#resultDisease').html('<p>An error occurred: ' + error + '</p>');

            }
        });

    }

</script>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Desh Clinic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/fontawesome.min.css" integrity="sha512-UuQ/zJlbMVAw/UU8vVBhnI4op+/tFOpQZVT+FormmIEhRSCnJWyHiBbEVgM4Uztsht41f3FzVWgLuwzUqOObKw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Desh Clinic</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area=""
                                       asp-controller="Authentication" asp-action="Logout">Log Out</a>
                                </li>
                            </ul>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Desh Clinic
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_Ncd.cshtml
<div class="row mt-3">

    <div class="col-md-3">

        <input type="text"
               id="newNcd"
               class="form-control" placeholder="NCD Name" />

    </div>

    <div class="col-md-2">

        <button type="button"
                id="saveNcd"
                data-id="0"
                class="btn btn-success disabled">
            Save
        </button>


    </div>

    <div class="col-md-4">
        <div id="result"></div>
    </div>

</div>

<div class="row  mt-2">

    <div class="col-md-12"
         style="height: 250px; overflow-y: scroll">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody id="ncdList">
            </tbody>
        </table>

        <div class="ncdListLoader">
            <div style="text-align: center">
                <img src="~/assets/images/loader.gif" />
            </div>
        </div>

    </div>

</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    $(document).ready(function (e) {


        NcdLoad();

    });


    $(document).on("keyup", "#newNcd", function (e) {

        $('#result').html("");

        if ($(this).val().trim() == "") {

            $("#saveNcd").addClass("disabled");

        } else {

            $("#saveNcd").removeClass("disabled");
        }

    });



    $(document).on("click", "#saveNcd", function (e) {

        ButtonLoaderShow("#saveNcd");

        var id = 0;

        if ($(this).text() == "Update") {

            id = $(this).attr("data-id");

        }

        var data = {
            ID: id,
            Name: $("#newNcd").val()
        }


        $.ajax({
            url: '@Url.Action("NcdSave", "Home")',
            type: 'POST',
            contentType: 'application/json',
            data: JSON.stringify(data),
            success: function (res) {

                if (res.error == "") {

                    $('#result').html(res.message);
                    $("#saveNcd").text("Save");
                    NcdLoad();

                } else {

                    $('#result').html(res.error);

                }

            },
            error: function (xhr, status, error) {
                $('#result').html('<p>An error occurred: ' + error + '</p>');
            }
        });

    });

    $(document).on("click", ".ncdListEdit", function (e) {

        var data = $(this).parents("tr");

        var id = data.attr("data-id");
        var name = data.attr("data-name");

        $("#saveNcd").attr("data-id", id);
        $("#newNcd").val(name);

        $("#saveNcd").removeClass("disabled");
        $("#saveNcd").text("Update");
        $("#result").html("");
    });

    $(document).on("click", ".ncdListDelete", function (e) {

        var parent = $(this).parents("tr");
        var id = parent.attr("data-id");
        parent.remove();


        $.ajax({
            url: 'Home/Delete/' + id,
            type: 'POST',
            contentType: 'application/json',
            success: function (res) {

                if (res.error == "") {

                    $("#saveNcd").text("Save");
                    $('#result').html(res.message);


                } else {

                    $('#result').html(res.error);

                }

            },
            error: function (xhr, status, error) {
                $('#result').html('<p>An error occurred: ' + error + '</p>');
            }
        });





    });

    function NcdLoad() {


        LoaderOneShow(".ncdListLoader");

        $.ajax({
            url: '@Url.Action("NcdList", "Partial")',
            type: 'GET',
            dataType: 'html',
            success: function (res) {

                LoaderOneHide(".ncdListLoader");
                $("#ncdList").html(res);

            },
            error: function (xhr, status, error) {
                $('#result').html('<p>An error occurred: ' + error + '</p>');
            }
        });

    }

</script>

WebApp/Views/Shared/_Patients.cshtml
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet" />

<div class="row mt-3">

    <div class="col-md-6">
    </div>


    <div class="col-md-6">
        <a href="/Home/PatientEntry">
            <button type="button"
                    data-id="0"
                    style="float: right"
                    class="btn btn-success">
                Patient Entry
            </button>
        </a>

    </div>

</div>

<div class="row  mt-2">

    <div class="col-md-12"
         style="height: 250px; overflow-y: scroll">

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" class="text-center">Patient ID</th>
                    <th scope="col">Patient Name</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody id="patientList">
            </tbody>
        </table>

        <div class="patientListLoader">
            <div style="text-align: center">
                <img src="~/assets/images/loader.gif" />
            </div>
        </div>
    </div>

</div>

<!-- Modal -->
<div class="modal fade" id="patientListDetailsModal" tabindex="-1"
     aria-labelledby="patientListDetailsModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Patient Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body patientDetails">
               
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    $(document).ready(function (e) {


        PatientLoad();

    });



    $(document).on("click", ".patientListDetails", function (e) {

        LoaderOneShow(".patientDetails");

        var parent = $(this).parents("tr");
        var id = parent.attr("data-id");

        $.ajax({
            url: 'Partial/PatientsDetails/' + id,
            type: 'GET',
            dataType: 'html',
            success: function (res) {
                LoaderOneHide(".patientDetails");
                $(".patientDetails").html(res);

            },
            error: function (xhr, status, error) {
               
            }
        });





    });

    function PatientLoad() {

        LoaderOneShow(".patientListLoader");

        $.ajax({
            url: '@Url.Action("PatientList", "Partial")',
            type: 'GET',
            dataType: 'html',
            success: function (res) {

                LoaderOneHide(".patientListLoader");
                $("#patientList").html(res);

            },
            error: function (xhr, status, error) {


            }
        });

    }

</script>